name: release-binaries

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: arm-unknown-linux-gnueabihf
          args: "--release"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "LICENSE,target/arm-unknown-linux-gnueabihf/release/plato-dropbox"
